sonar.organization=krealalejo
sonar.projectKey=krealalejo_kra-web-frontend-nuxt
sonar.projectName=kra-web-frontend-nuxt
sonar.host.url=https://sonarcloud.io

sonar.sources=app,server
sonar.exclusions=**/.nuxt/**,**/node_modules/**,**/.output/**,**/dist/**,**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/app/types/**
